import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Amir Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">AMIR JABALLAH CV </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Portfolio
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Amir JABALLAH
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Etudiant
            </h3>
           <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
                 <a href="https://www.linkedin.com/in/amir-jaballah-5803b312a/" target="_blank" rel="noopener noreferrer">
                   <AiFillLinkedin />
                 </a>
            </div>
          </div>
        </section>
        <section>
          <div>
          <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
          <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">  
          <h2>PROFIL</h2> 
Actuellement en deuxième année de master professionnel en Ingénierie
du Logiciel - Open Source à ISI, je suis activement à la recherche d'une
opportunité de stage pour mon projet de fin d'études dans le domaine du
développement. Doté d'une grande autonomie et d'une volonté marquée,
je suis prêt à mettre en valeur mes compétences et ma soif
d'apprentissage au service de votre entreprise.</div>
            </p>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">  

            <h3 className="text-3xl py-1 dark:text-white ">FORMATION:</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
          
            <h2><b>Mastère Professionnel en Génie Logiciel MP2L, 09/2022 – En cours </b></h2>
            <p>Institut Supérieur D'Informatique Et Université Virtuelle De Tunis – Ariana</p>

<h2><b>Ingénierie Électique , 09/2014 – 09/2018</b></h2>
<p>Ecole Nationale D'ingénieurs De Sfax – Sfax, Tunisie</p>

<h2><b>Cycle préparatoire specialité technologie , 09/2012 – 06/2014</b></h2>
<p>Institut Préparatoire Aux Etudes D'ingénieurs De Nabeul – Nabeul, Tunisie</p>

<h2><b>Baccalauréat : Sciences Techniques, 09/2011 – 06/2012</b></h2>
<p>Lycée Technique De Médenine – Medenine, Tunisie – Bien</p>

 </p></div>
 <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">  
 <h3 className="text-3xl py-1 dark:text-white ">EXPERIENCES:</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">    
            <h2><b>Project Manager</b></h2>
            <p><em>Société Slama Technique Avancée Du Froid (STAF) - Tunis</em></p>
            <h2>08/2020 - Actuel</h2>
            <p>
• Conception et réalisation de projets nécessitant un refroidissement
industriel ou commercial</p>
<p>•Etude et conception d'armoires électriques et régulation avec
intégration des systèmes d'automate programmable industriel et de
gestion technique centralisée GTC</p>
<p>• Elaboration des plans en utilisant AutoCAD et SolidWorks</p>
<p>• Assurer le suivi de la mise en œuvre des chambres froides</p>
<p>• Organisation des plannings et distribution des tâches au personnel.</p>
<p>• Coordination de l'activité de l'équipe au quotidien.Négociation et construction des projets, rédaction d'offres
commerciales sur-mesure, soutien méthodologique et organisationnel
dans la gestion des projets.</p>
<p>• Réponse aux appels d'offres : constitution et rédaction des dossiers,
chiffrage des propositions</p>
<h2><b>Responsable Projet</b> </h2>
<p><em>Tunisie Electro Technique (TET) - Tunis</em></p>
<h2>01/2020 - 07/2020 </h2>
<p>• Faire l'étude et la conception des armoires électrique basse et moyen tension.</p>
<p>• Elaboration des plans par AutoCAD et SEE Electrical.</p>
<p>• Suivi des projets.</p>
            </p>
            </div>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
              Compétences technique:
              </h3>
              <p className="py-2">
              </p>
              <h4 className="py-4 text-teal-600">AutoCAD</h4>
              <p className="py-4 text-teal-600">SolidWorks</p>
              <p className="py-4 text-teal-600">iso9001</p>
              <p className="py-4 text-teal-600">photovoltaique</p>
              <p className="py-4 text-teal-600">froid industriel</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                 Compétences Informatique:
              </h3>
              <p className="py-2">
              </p>
              <h4 className="py-4 text-teal-600">programmation </h4>
              <p className="py-4 text-teal-600">Java</p>
              <p className="py-4 text-teal-600">NodeJs</p>
              <p className="py-4 text-teal-600">C/C++</p>
              <p className="py-4 text-teal-600">Python</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Certifications</h3>
              <p className="py-2">
              </p>
              <h4 className="py-4 text-teal-600">Arduino</h4>
              <p className="py-4 text-teal-600">Raspberry</p>
              <p className="py-4 text-teal-600">C/C++</p>
              <p className="py-4 text-teal-600">Tia Portal Siemens</p>
            </div> 
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Languages:</h3>  
              <p className="py-2">
              </p>  
              <p className="text-gray-800 py-1">Arabe:natif</p>
              <p className="text-gray-800 py-1">Français:Courant</p>
              <p className="text-gray-800 py-1">Anglais:Intermédiaire</p>
            </div></div>
        </section>
      </main>
    </div>
  );
}