import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Amir Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">AMIR JABALLAH CV </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  CV
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Amir JABALLAH
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Etudiant
            </h3>
         
           <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
                 <a href="https://www.linkedin.com/" target="_blank" rel="noopener noreferrer">
                   <AiFillLinkedin />
                 </a>
            </div>

           
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
          <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
          PROFIL
Actuellement en deuxième année de master professionnel en Ingénierie
du Logiciel - Open Source à ISI, je suis activement à la recherche d'une
opportunité de stage pour mon projet de fin d'études dans le domaine du
développement. Doté d'une grande autonomie et d'une volonté marquée,
je suis prêt à mettre en valeur mes compétences et ma soif
d'apprentissage au service de votre entreprise.
            </p>
            <h3 className="text-3xl py-1 dark:text-white ">FORMATION:</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            
Mastère Professionnel en Génie Logiciel MP2L, 09/2022 – En cours
Institut Supérieur D'Informatique Et Université Virtuelle De Tunis – Ariana

Ingénierie Électique , 09/2014 – 09/2018
Ecole Nationale D'ingénieurs De Sfax – Sfax, Tunisie

09/2012 – 06/2014
Institut Préparatoire Aux Etudes D'ingénieurs De Nabeul – Nabeul, Tunisie

Baccalauréat : Sciences Techniques, 09/2011 – 06/2012
Lycée Technique De Médenine – Medenine, Tunisie – Bien

 </p>
            </p>
              <h3 className="text-3xl py-1 dark:text-white ">Education:</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            <h2>September 20222 - June 2024: Master degree in Software Engineering</h2>
            <p><em>Speciality:</em> Software Engineering</p>
  <p><em>Institution:</em> Higher Institute of Computer Science of Tunis</p>

  <h2>September 2014 - September 2015: Master Degree in Composite Materials</h2>
  <p><em>Speciality:</em> Materials Engineering</p>
  <p><em>Institution:</em> Le Havre Univeristy</p>

  <h2>September 2010 - June 2013 : Engineering Degree in Materials sciences</h2>
  <p><em>Speciality:</em> Materials Engineering</p>
  <p><em>Institution:</em> National Engineering School Of Sfax</p>

  <h2>September 2008 - June 2010 :  Preparotry Class </h2>
  <p><em>Speciality:</em> Mathematics and Physics (MP)</p>
  <p><em>Institution:</em>  Preparatory Institute for Engineering Studies of Sfax</p>

  <h2>September 2007 - June 2008: Baccalaureate Degree</h2>
  <p><em>Specialty:</em> Baccalaureate Degree in Mathematics</p>
  Project Manager
Société Slama Technique Avancée Du Froid (STAF) - Tunis
08/2020 - Actuel

  Conception et réalisation de projets nécessitant un refroidissement
industriel ou commercial
•
Etude et conception d'armoires électriques et régulation avec
intégration des systèmes d'automate programmable industriel et de
gestion technique centralisée GTC
•
• Elaboration des plans en utilisant AutoCAD et SolidWorks
• Assurer le suivi de la mise en œuvre des chambres froides
• Organisation des plannings et distribution des tâches au personnel.
• Coordination de l'activité de l'équipe au quotidien.
Négociation et construction des projets, rédaction d'offres
commerciales sur-mesure, soutien méthodologique et organisationnel
dans la gestion des projets.
•
Réponse aux appels d'offres : constitution et rédaction des dossiers,
chiffrage des propositions

Responsable Projet
Tunisie Electro Technique (TET) - Tunis
01/2020 - 07/2020


Faire l'étude et la conception des armoires électrique basse et moyen
tension.
•
• Elaboration des plans par AutoCAD et SEE Electrical.
• Suivi des projets.

            </p>
          </div>
          

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
              compétences:
              </h3>
              <p className="py-2">
              </p>
              <h4 className="py-4 text-teal-600">Test Automation</h4>
              <p className="text-gray-800 py-1">Writing test cases</p>
              <p className="text-gray-800 py-1">Selenium and Cypress</p>
              <p className="text-gray-800 py-1">API implimentation and testing</p>
              <p className="text-gray-800 py-1">Cucumber, BDD, CI/CD</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                 compétences:
              </h3>
              <p className="py-2">
                compétences
              </p>
              <h4 className="py-4 text-teal-600">programmation </h4>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">NodeJs</p>
              <p className="text-gray-800 py-1">C/C++</p>
              <p className="text-gray-800 py-1">Python</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">skills</h3>
              <p className="py-2">
              Certifications
              </p>
              <h4 className="py-4 text-teal-600">IBM: Linux and Private Cloud Administration</h4>
              <p className="text-gray-800 py-1">GASQ: A4Q Selenium Java </p>
              <p className="text-gray-800 py-1">GASQ: ISTQB: Certified Tester Foundation Level</p>
              <p className="text-gray-800 py-1">Scrum Fundemental Certified</p>
            </div>
          </div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">skills</h3>
              <p className="py-2">
              
              </p>
              <h2 className="py-4 text-teal-600">Languages:</h2>
            
              <p className="text-gray-800 py-1">Arabic: Native</p>
              <p className="text-gray-800 py-1">French: Fluent</p>
              <p className="text-gray-800 py-1">English: Intermediate</p>
            </div>
        </section>
      </main>
    </div>
  );
}